# Dependencies
markdown: redcarpet
highlighter:  pygments

# Permalinks
#
# Use of 'relative_permalinks' ensures post links from the index work properly.
permalink:  pretty
relative_permalinks:  true

# Setup
title:  Caleb White
tagline:  'A freelance software developer and writer.'
description:  "Caleb White's thoughts on software development, personal development and writing."
url:  http://whiteworkroom.com
baseurl:  /
avatar: media/images/caleb-white-avatar.png
paginate: 5
locale: en_us

# About/contact
author:
  name: Caleb White
  email:  contact@whiteworkroom.com
fb_admins:  https://www.facebook.com/profile.php?id=100010940163439&ref=br_rs
fb_appid: 100010940163439

gems:
  - jekyll-sitemap
  - jekyll-redirect-from