# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: White Workroom || Caleb White Online Portfolio
email: calebwh96@me.com
description: > # this means to ignore newlines until "baseurl:"
  Online portfolio of Caleb White, photography and Web Design | Charleston | South Carolina | United States |
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whiteworkroom.com" # the base hostname & protocol for your site
twitter_username: calebwh96
github_username:  whiteworkroom

# Build settings
markdown: kramdown
gems: jekyll-sitemap
